package net.qzimyion.cellulose.items;

import net.minecraft.item.ItemGroups;

import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;

import static net.minecraft.item.Items.*;
import static net.qzimyion.cellulose.blocks.CelluloseBlocks.*;
import static net.qzimyion.cellulose.items.CelluloseItems.*;

@SuppressWarnings("UnstableApiUsage")
public class CelluloseItemGroups
{
    public static void registerItemGroups()
    {
        //This section adds items to ingredients group
        ItemGroupEvents.modifyEntriesEvent(ItemGroups.INGREDIENTS).register( content-> content.addAfter(EGG, PIPIS));

        /* This section adds items to building blocks group */

        ItemGroupEvents.modifyEntriesEvent(ItemGroups.BUILDING_BLOCKS).register(content -> {
            /* Section 1: Vertical Planks */
            content.addAfter(OAK_SLAB, VERTICAL_OAK_PLANKS, VERTICAL_OAK_PLANKS_STAIRS, VERTICAL_OAK_PLANKS_SLABS);
            content.addAfter(BIRCH_SLAB, VERTICAL_BIRCH_PLANKS, VERTICAL_BIRCH_PLANKS_STAIRS, VERTICAL_BIRCH_PLANKS_SLABS);
            content.addAfter(SPRUCE_SLAB, VERTICAL_SPRUCE_PLANKS, VERTICAL_SPRUCE_PLANKS_STAIRS, VERTICAL_SPRUCE_PLANKS_SLABS);
            content.addAfter(DARK_OAK_SLAB, VERTICAL_DARK_OAK_PLANKS, VERTICAL_DARK_OAK_PLANKS_STAIRS, VERTICAL_DARK_OAK_PLANKS_SLABS);
            content.addAfter(ACACIA_SLAB, VERTICAL_ACACIA_PLANKS, VERTICAL_ACACIA_PLANKS_STAIRS, VERTICAL_ACACIA_PLANKS_SLABS);
            content.addAfter(JUNGLE_SLAB, VERTICAL_JUNGLE_PLANKS, VERTICAL_JUNGLE_PLANKS_STAIRS, VERTICAL_JUNGLE_PLANKS_SLABS);
            content.addAfter(CRIMSON_SLAB, VERTICAL_CRIMSON_PLANKS, VERTICAL_CRIMSON_PLANKS_STAIRS, VERTICAL_CRIMSON_PLANKS_SLABS);
            content.addAfter(WARPED_SLAB, VERTICAL_WARPED_PLANKS, VERTICAL_WARPED_PLANKS_STAIRS, VERTICAL_WARPED_PLANKS_SLABS);
            content.addAfter(MANGROVE_SLAB, VERTICAL_MANGROVE_PLANKS, VERTICAL_MANGROVE_PLANKS_STAIRS, VERTICAL_MANGROVE_PLANKS_SLABS);
            content.addAfter(BAMBOO_SLAB, VERTICAL_BAMBOO_PLANKS, VERTICAL_BAMBOO_PLANKS_STAIRS, VERTICAL_BAMBOO_PLANKS_SLABS);
            content.addAfter(CHERRY_SLAB, VERTICAL_CHERRY_PLANKS, VERTICAL_CHERRY_PLANKS_STAIRS, VERTICAL_CHERRY_PLANKS_SLABS);

            /*Section 2: Mosaic Blocks*/

            content.addAfter(STRIPPED_OAK_WOOD, OAK_MOSAIC, OAK_MOSAIC_STAIRS, OAK_MOSAIC_SLABS);
            content.addAfter(STRIPPED_BIRCH_WOOD, BIRCH_MOSAIC, BIRCH_MOSAIC_STAIRS, BIRCH_MOSAIC_SLABS);
            content.addAfter(STRIPPED_SPRUCE_WOOD, SPRUCE_MOSAIC, SPRUCE_MOSAIC_STAIRS, SPRUCE_MOSAIC_SLABS);
            content.addAfter(STRIPPED_DARK_OAK_WOOD, DARK_OAK_MOSAIC, DARK_OAK_MOSAIC_STAIRS, DARK_OAK_MOSAIC_SLABS);
            content.addAfter(STRIPPED_JUNGLE_WOOD, JUNGLE_MOSAIC, JUNGLE_MOSAIC_STAIRS, JUNGLE_MOSAIC_SLABS);
            content.addAfter(STRIPPED_ACACIA_WOOD, ACACIA_MOSAIC,ACACIA_MOSAIC_STAIRS, ACACIA_MOSAIC_SLABS);
            content.addAfter(STRIPPED_CRIMSON_HYPHAE, CRIMSON_MOSAIC, CRIMSON_MOSAIC_STAIRS, CRIMSON_MOSAIC_SLABS);
            content.addAfter(STRIPPED_WARPED_HYPHAE, WARPED_MOSAIC, WARPED_MOSAIC_STAIRS, WARPED_MOSAIC_SLABS);
            content.addAfter(STRIPPED_MANGROVE_WOOD, MANGROVE_MOSAIC, MANGROVE_MOSAIC_STAIRS, MANGROVE_MOSAIC_SLABS);
            content.addAfter(STRIPPED_CHERRY_WOOD, CHERRY_MOSAIC, CHERRY_MOSAIC_STAIRS, CHERRY_MOSAIC_SLABS);

            /*Section 3: Lintels*/

            content.addAfter(VERTICAL_OAK_PLANKS_SLABS, OAK_FRAME, OAK_LINTELS);
            content.addAfter(VERTICAL_BIRCH_PLANKS_SLABS, BIRCH_FRAME, BIRCH_LINTELS);
            content.addAfter(VERTICAL_SPRUCE_PLANKS_SLABS, SPRUCE_FRAME, SPRUCE_LINTELS);
            content.addAfter(VERTICAL_DARK_OAK_PLANKS_SLABS, DARK_OAK_FRAME, DARK_OAK_LINTELS);
            content.addAfter(VERTICAL_JUNGLE_PLANKS_SLABS, JUNGLE_FRAME, JUNGLE_LINTELS);
            content.addAfter(VERTICAL_ACACIA_PLANKS_SLABS, ACACIA_FRAME, ACACIA_LINTELS);
            content.addAfter(VERTICAL_CRIMSON_PLANKS_SLABS, CRIMSON_FRAME, CRIMSON_LINTELS);
            content.addAfter(VERTICAL_WARPED_PLANKS_SLABS, WARPED_FRAME, WARPED_LINTELS);
            content.addAfter(VERTICAL_MANGROVE_PLANKS_SLABS, MANGROVE_FRAME, MANGROVE_LINTELS);
            content.addAfter(VERTICAL_BAMBOO_PLANKS_SLABS, BAMBOO_FRAME, BAMBOO_LINTELS);
            content.addAfter(VERTICAL_CHERRY_PLANKS_SLABS, CHERRY_FRAME, CHERRY_LINTELS);
            content.addAfter(VERTICAL_CACTUS_PLANKS_SLABS, CACTUS_FRAME, CACTUS_LINTELS);

            /*Section 4: Engraved logs and wood*/

            content.addAfter(STRIPPED_OAK_WOOD, ENGRAVED_OAK, ENGRAVED_OAK_WOOD);
            content.addAfter(STRIPPED_BIRCH_WOOD, ENGRAVED_BIRCH, ENGRAVED_BIRCH_WOOD);
            content.addAfter(STRIPPED_SPRUCE_WOOD, ENGRAVED_SPRUCE, ENGRAVED_SPRUCE_WOOD);
            content.addAfter(STRIPPED_DARK_OAK_WOOD, ENGRAVED_DARK_OAK, ENGRAVED_DARK_OAK_WOOD);
            content.addAfter(STRIPPED_JUNGLE_WOOD, ENGRAVED_JUNGLE, ENGRAVED_JUNGLE_WOOD);
            content.addAfter(STRIPPED_ACACIA_WOOD, ENGRAVED_ACACIA, ENGRAVED_ACACIA_WOOD);
            content.addAfter(STRIPPED_CRIMSON_HYPHAE, ENGRAVED_CRIMSON, ENGRAVED_CRIMSON_HYPHAE);
            content.addAfter(STRIPPED_WARPED_HYPHAE, ENGRAVED_WARPED, ENGRAVED_WARPED_HYPHAE);
            content.addAfter(STRIPPED_MANGROVE_WOOD, ENGRAVED_MANGROVE, ENGRAVED_MANGROVE_WOOD);
            content.addAfter(STRIPPED_CHERRY_WOOD, ENGRAVED_CHERRY, ENGRAVED_CHERRY_WOOD);

            /*Section 5: Chipped logs, wood and planks*/
            content.addAfter(ENGRAVED_OAK_WOOD, CHIPPED_OAK, CHIPPED_OAK_WOOD, CHIPPED_OAK_PLANKS, CHIPPED_OAK_PLANKS_STAIRS, CHIPPED_OAK_PLANKS_SLABS);
            content.addAfter(ENGRAVED_BIRCH_WOOD, CHIPPED_BIRCH, CHIPPED_BIRCH_WOOD, CHIPPED_BIRCH_PLANKS, CHIPPED_BIRCH_PLANKS_STAIRS, CHIPPED_BIRCH_PLANKS_SLABS);
            content.addAfter(ENGRAVED_SPRUCE, CHIPPED_SPRUCE, CHIPPED_SPRUCE_WOOD, CHIPPED_SPRUCE_PLANKS, CHIPPED_SPRUCE_PLANKS_STAIRS, CHIPPED_SPRUCE_PLANKS_SLABS);
            content.addAfter(ENGRAVED_DARK_OAK_WOOD, CHIPPED_DARK_OAK, CHIPPED_DARK_OAK_WOOD, CHIPPED_DARK_OAK_PLANKS, CHIPPED_DARK_OAK_PLANKS_STAIRS, CHIPPED_DARK_OAK_PLANKS_SLABS);
            content.addAfter(ENGRAVED_JUNGLE, CHIPPED_JUNGLE, CHIPPED_JUNGLE_WOOD, CHIPPED_JUNGLE_PLANKS, CHIPPED_JUNGLE_PLANKS_STAIRS, CHIPPED_JUNGLE_PLANKS_SLABS);
            content.addAfter(ENGRAVED_ACACIA, CHIPPED_ACACIA, CHIPPED_ACACIA_WOOD, CHIPPED_ACACIA_PLANKS, CHIPPED_ACACIA_PLANKS_STAIRS, CHIPPED_ACACIA_PLANKS_SLABS);
            content.addAfter(ENGRAVED_CRIMSON_HYPHAE, CHIPPED_CRIMSON, CHIPPED_CRIMSON_HYPHAE, CHIPPED_CRIMSON_PLANKS, CHIPPED_CRIMSON_PLANKS_STAIRS, CHIPPED_CRIMSON_PLANKS_SLABS);
            content.addAfter(ENGRAVED_WARPED_HYPHAE, CHIPPED_WARPED, CHIPPED_WARPED_HYPHAE, CHIPPED_WARPED_PLANKS, CHIPPED_WARPED_PLANKS_STAIRS, CHIPPED_WARPED_PLANKS_SLABS);
            content.addAfter(ENGRAVED_MANGROVE_WOOD, CHIPPED_MANGROVE, CHIPPED_MANGROVE_WOOD, CHIPPED_MANGROVE_PLANKS, CHIPPED_MANGROVE_PLANKS_STAIRS, CHIPPED_MANGROVE_PLANKS_SLABS);
            content.addAfter(ENGRAVED_CHERRY_WOOD, CHIPPED_CHERRY, CHIPPED_CHERRY_WOOD, CHIPPED_CHERRY_PLANKS, CHIPPED_CHERRY_PLANKS_STAIRS, CHIPPED_CHERRY_PLANKS_SLABS);
            content.addAfter(BAMBOO_BLOCK, CHIPPED_BAMBOO_BLOCK, CHIPPED_BAMBOO_WOOD, CHIPPED_BAMBOO_PLANKS, CHIPPED_BAMBOO_PLANKS_STAIRS, CHIPPED_BAMBOO_PLANKS_SLABS);
            content.addAfter(ENGRAVED_CACTUS_CROWN, CHIPPED_CACTUS, CHIPPED_CACTUS_CROWN, CHIPPED_CACTUS_PLANKS, CHIPPED_CACTUS_PLANKS_STAIRS, CHIPPED_CACTUS_PLANKS_SLABS);

            /*Section 6: Glazed wood*/

            /*Section 7: Carved wood*/

            /*Section 8: Carpented wood*/

            /*Section 9: Barricades*/

            /*Section 10: */
        });

        // Functional blocks
        ItemGroupEvents.modifyEntriesEvent(ItemGroups.FUNCTIONAL).register(content -> content.addAfter(STONECUTTER, SAWMILL));

        ItemGroupEvents.modifyEntriesEvent(ItemGroups.TOOLS).register(content -> content.addAfter(WET_SPONGE, BLOCK_OF_PAPER, BLOCK_SOAKED_OF_PAPER));

        //Cactus woodset
        ItemGroupEvents.modifyEntriesEvent(ItemGroups.BUILDING_BLOCKS).register(content -> content.addAfter(WARPED_BUTTON, CACTUS_BUNDLE, CACTUS_CROWN, STRIPPED_CACTUS, STRIPPED_CACTUS_CROWN, ENGRAVED_CACTUS, ENGRAVED_CACTUS_CROWN,
                CACTUS_MOSAIC, CACTUS_MOSAIC_STAIRS, CACTUS_MOSAIC_SLABS, CACTUS_PLANKS, CACTUS_STAIRS, CACTUS_SLABS, VERTICAL_CACTUS_PLANKS, VERTICAL_CACTUS_PLANKS_STAIRS,
                VERTICAL_CACTUS_PLANKS_SLABS, CACTUS_FENCE, CACTUS_FENCE_GATE, CACTUS_DOOR, CACTUS_TRAPDOOR, CACTUS_PRESSURE_PLATE, CACTUS_BUTTON
        ));
    }

}
